#yUML source 1.11

[Pelivelho]
[Pelaaja]
[Poyta]
[Merkkihenkilo]
[Kasakokoelma]
[Omaisuus]
[Omaisuusvaatimus]
[Varaus]
[Enum:Vari]
[Omistus]
[Nallekarkkikasa]

[Pelivelho]-[Poyta]
[Pelivelho]-[Pelaaja]
[Poyta]-[Pelaaja]
[Poyta]-[Omaisuus]
[Poyta]-[Kasakokoelma]
[Poyta]-[Merkkihenkilo]
[Pelaaja]-[Merkkihenkilo]
[Pelaaja]-[Kasakokoelma]
[Pelaaja]-[Omaisuus]
[Pelaaja]-[Varaus]
[Merkkihenkilo]-[Omaisuusvaatimus]
[Kasakokoelma]-[Nallekarkkikasa]
[Omaisuus]-[Omistus]
[Omistus]-[Enum:Vari]
[Omistus]-[Nallekarkkikasa]
[Varaus]-[Omistus]
[Omaisuusvaatimus]-[Enum:Vari]
[Nallekarkkikasa]-[Enum:Vari]

